name: Deploy to Azure Container Apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build and Test
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  # Job 2: Build and Push Docker Image
  build-and-push-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Log in to Azure Container Registry
      - name: Azure Login
        #uses: azure/docker-login@v1
        uses: azure/login@v1
        # with:
        #   login-server: aibookpublisheragentic.azurecr.io
        #   username: ${{ secrets.ACR_USERNAME }}
        #   password: ${{ secrets.ACR_PASSWORD }}
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Test ACR access
        run: |
          az account show
          az acr show --name aibookpublisheragentic

      - name: Login to Azure Container Registry
        run: az acr login --name aibookpublisheragentic

      - name: Build and push Docker image 
        run: |
          docker build --no-cache -t aibookpublisheragentic.azurecr.io/ai-book-publisher:latest .
          docker push aibookpublisheragentic.azurecr.io/ai-book-publisher:latest

  # Job 3: Deploy to Azure Container Apps
  deploy-to-azure:
    needs: build-and-push-image # it basically ensure the previous needed jobs success
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # it ensures if git repo head is main
    environment: ai-book-production # reference to github env

    steps:
    - name: Azure Login
      uses: azure/login@v1 
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps 
      run: |
        az containerapp create \
          --name ${{ vars.CONTAINER_APP_NAME }} \
          --resource-group ${{ vars.RESOURCE_GROUP }} \
          --environment ${{ vars.CONTAINER_APP_ENV }} \
          --image ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ vars.CONTAINER_NAME }}:latest \
          --target-port 8080 \
          --ingress external \
          --registry-server ${{ vars.AZURE_CONTAINER_REGISTRY }}.azurecr.io \
          --registry-username ${{ secrets.ACR_USERNAME }} \
          --registry-password ${{ secrets.ACR_PASSWORD }} \
          --env-vars \
            STREAMLIT_SERVER_PORT=8080 \
            STREAMLIT_SERVER_ADDRESS=0.0.0.0 \
            STREAMLIT_SERVER_HEADLESS=true
      



